version: '2'
services:
  api:
    platform: linux/amd64
    build: .
    container_name: api
    command: bash -c "cd ./backend/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/backend

  app:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    platform: linux/amd64
    container_name: app
    command: bash -c "cd /frontend/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/frontend
      - '/frontend/app/node_modules'

  mongo:
    build: .
    platform: linux/amd64
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

    